# Model type to API client
MODEL2API:
  gpt-4o: "openai"
  gpt-4o-mini: "openai"


# Story length
MAX_CHAPTERS: 5
MAX_STAGES: 5

# prompts
SYSTEM_PROMPT: "你是一位网络小说作家。"
#SYSTEM_PROMPT: "你是一位富有创意的小说生成器，擅长创作精彩的情节、深刻的人物和引人入胜的故事背景。无论是奇幻、科幻、悬疑、惊悚、搞笑还是爱情小说，你都能根据提示生动地呈现情节发展，创造真实且细腻的角色对话。请根据用户提供的关键字或情境创作出丰富的故事片段，使读者沉浸在你构建的虚拟世界中。"

STORYTELLING_SYSTEM_PROMPT: >
  视角：视角为上帝视角，读者知道每个人物的行为动机，和心里活动。 \n
  读者群体：15到25岁的少女或者女性群体，晋江网站的读者。 \n
  文风：幽默风趣，俏皮，充满着女性的可爱和柔美。 \n
  段落风格：多换行，少用长句子，多用对话推进情节，避免过多的解释。 \n
  情节：可以按照你的理解增加新的故事情节，如果你觉得当前的情节不足以支撑过多的字数情节，你可以按照你的理解来丰富内容，甚至创造新的支线剧情。 \n
  避免重复：不仅避免相同的句子、情节、对话、场景描述和情感表达，还要确保任何重复的信息都能有所不同地呈现，以增加故事层次感，减少冗余感。 \n
  剧情快速推进：在每一章或每一个重要场景中，确保有推动情节发展的事件或决策。减少缓慢的内心独白或背景介绍，通过角色的行动和对话来展示故事关键要素。 \n
  连贯无断层：每个情节的承接点应自然流畅，从一个场景进入下一个场景时，合理描述事件或情绪的变化，避免突然的情节转折让读者感到突兀。 \n
  起承转合清晰：在每个段落或章节中，设置小的高潮和转折，并为主要情节做好铺垫，使读者能够循序渐进地融入情节发展。 \n
  无意义的对话和场景减少：确保每一句对话、每一个场景都具有明确的情节功能（推动情节或展现角色性格）。无实质内容的对话避免出现，每一场景的描写都应紧扣情节或人物发展。 \n
  多换行、少用长句：增加视觉上的“喘息”空间，使用短句增强节奏感。在描述情绪时用简练的词汇，不冗长，保证阅读时顺畅。 \n
  语言流畅自然：选用简洁明了的现代用词，减少过多修饰，避免用过于冗杂或华丽的语言，特别是在紧张的情节或情绪描写中。 \n
  情感和情绪的准确表达：用更直接、精准的方式表达人物情绪，避免含糊或过于抽象的情感表述。情感逐步递进，增加人物情感的张力。 \n
  视觉与情境感的渲染：在环境描写中，用简洁而富有画面的文字，将场景“画”出来，使读者更容易融入。

 
OUTLINE_PROMPT: >
  请根据以下关键词生成一段小说剧情大纲，包括故事的主要冲突、关键转折点以及结局走向，使读者对剧情有清晰的理解。大纲仅需100字左右即可。要求与关键词尽量相关即可，如果加入关键词会导致表达不自然，则无需强行在大纲中出现关键词。\n 
  关键词：{hint}

STYLE_PROMPT: >
  请根据以下小说大纲随机选择一种适合的文风。文风类型包括但不限于：轻松幽默风、热血激情风、暗黑深沉风、温馨治愈风、高智谋略风、唯美细腻风、快节奏爽文风，等。 仅需输出一句简短的文风类型描述即可。 \n 小说大纲：{outline}"

CHARACTER_PROMPT: "请基于以下小说大纲和文风类型设计出场人物，包括主角、主角的同伴和反派，每个角色包含姓名、阵营和简要背景。输出格式为 JSON 格式的字典，格式如下：\n {{角色列表: [{{姓名: 姓名A, 阵营: 主角同伴, 角色背景: 角色背景社交}}]}}。\n 小说大纲：{outline} \n 文风类型：{story_style}"

CHAPTER_PROMPT: "请根据以下小说大纲，文风类型和出场角色列表，生成五个章节的剧情大纲。每个章节包含主要剧情和出场角色，输出格式为 JSON 格式的字典，格式如下：\n {{章节大纲: [{{章节序号: 1, 标题: 章节标题, 出场角色: [角色A, 角色B], 剧情摘要: 本章节简要剧情概述}}]}} \n 小说大纲：{outline} \n 文风类型：{story_style} \n 出场角色：{characters}"

STORY_PROMPT: "请根据以下本章剧情摘要，文风类型，出场角色等信息生成小说章节。\n 要求剧情紧接前文，生成本章节的{stage_desc} \n\n 注意：\n {stage_notes} \n\n 本章剧情摘要：{chapter_outline} \n\n 文风类型: {story_style} \n\n 出场角色：{chapter_characters} \n\n 前文: {previous_story}" 


# stage prompts
STAGE_DESC_1: "开端阶段：引出故事背景，为整个故事奠定基础。"
STAGE_DESC_2: "递进阶段：事件开始推进，冲突或矛盾逐渐展开，使剧情逐渐紧张。"
STAGE_DESC_3: "高潮阶段：故事的关键转折点，通常是冲突或情感的最高点。"
STAGE_DESC_4: "回落阶段：高潮后的情节过渡，让读者看到冲突的后果和角色的变化。"
STAGE_DESC_5: 
  open: "结局阶段：本章故事在这里得到解决或闭合。同时承上启下引出下一章节。下一章节剧情摘要：{next_chapter_outline}"
  close: "结局与铺垫阶段：本章故事在这里得到解决或闭合，所有的主要问题都得到解答，情感归于平静。"

STAGE_NOTES_CONTINUE: "- 输出包含两个部分，即本章节当前阶段的小说本体内容，和紧接着本体内容，给读者的多种剧情选项，不同选项会导致不同结局。\n - 剧情选项应有四种，分别代表不同性格的主角行为，如善良或邪恶，守序或混乱，主动或被动等。\n - 输出格式为 JSON 格式的字典，参考样例如下：{{小说内容: 紧接上文的小说内容, 剧情选择: [选择1, 选择2, 选择3, 选择4]}}" 
STAGE_NOTES_LAST: "- 输出为本章节当前阶段的小说本体内容，和紧接着本体内容。\n - 输出格式为 JSON 格式的字典，参考样例如下：{{小说内容: 紧接上文的小说内容}}" 
